import { CellStyle } from '@syncfusion/excel-export';
import type { GridRef } from './grid.interfaces';
import type { ColumnProps } from './column.interfaces';

/**
 * Specifies the row range to include in an Excel export operation.
 *
 * - `All` — Exports every row from the full data source.
 * - `CurrentPage` — Exports only the rows visible on the current page.
 * - `Custom` — Exports rows within the range defined by `customRange`.
 */
export type ExcelExportRange = 'All' | 'CurrentPage' | 'Custom';

/**
 * Defines a zero-based inclusive row range for `Custom` Excel export.
 *
 * @example
 * ```typescript
 * const customRange: ExcelExportCustomRange = { startRow: 0, endRow: 49 }; // first 50 rows
 * ```
 */
export interface ExcelExportCustomRange {
    /**
     * Zero-based index of the first row to include (inclusive).
     *
     * @type {number}
     */
    startRow: number;

    /**
     * Zero-based index of the last row to include (inclusive).
     *
     * @type {number}
     */
    endRow: number;
}

/**
 * Options passed to `useExcelExport` hook to enable grid-aware data resolution.
 * Mirrors `UseGridPdfExportOptions` for consistent API parity.
 *
 * @template T - Generic type for the data source items
 * @example
 * ```typescript
 * const { excelExport } = useExcelExport({
 *   gridRef,
 *   getAllData: async (query) => await dataManager.executeQuery(query)
 * });
 * ```
 */
export interface UseGridExcelExportOptions<T = unknown> {
    /**
     * Reference to the Grid component instance.
     * Used to resolve `currentPage` data and column definitions.
     *
     * @type {React.RefObject<GridRef<T>>}
     */
    gridRef: React.RefObject<GridRef<T>>;

    /**
     * Optional callback to fetch all data from remote/custom source.
     * Invoked when `range` is `All` and data cannot be resolved locally.
     *
     * @param {unknown} query - Data query argument generated by the grid
     * @returns {Promise<T[]>} Resolved full dataset
     */
    getAllData?: (query: unknown) => Promise<T[]>;

    /**
     * Optional callback to supply custom column definitions for export.
     * Overrides visible grid columns when provided.
     *
     * @returns {ColumnProps[]} Column definitions
     */
    getColumns?: () => ColumnProps[];
}

/**
 * Return data from `useExcelExport`.
 * Exposes the export executor, progress status, loading state, and error data.
 */
export interface UseExcelExportReturn<T = unknown> {
    /** Export the grid data to Excel and return a Blob. */
    excelExport: (settings: ExcelExportSettings<T>) => Promise<Blob>;
    /** Progress as a percentage from 0 to 100. */
    progress: number;
    /** True while the export operation is active. */
    isExporting: boolean;
    /** Last error message, or null if no error occurred. */
    error: string | null;
}

/**
 * Options for configuring Excel export behavior.
 */
export interface ExportCell {
    /** Zero-based column index of the cell. */
    index: number;
    /** The value to display in the cell. */
    value: string | Date | number | boolean;
    /** Number of rows the cell should span. */
    rowSpan: number;
    /** Number of columns the cell should span. */
    colSpan: number;
    /** Optional styling for the cell. */
    style?: CellStyle;
    /** Optional hyperlink configuration for the cell. */
    hyperlink?: ExcelHyperlink;
}

/**
 * Workbook structure with optional worksheet images for Excel export.
 *
 * @private
 */
export interface WorkbookWithWorksheetImages {
    worksheets?: Array<{ images?: ExcelImage[] }>;
}


/**
 * Excel image metadata for cell export.
 */
export interface ExcelImage {
    /**
     * Base64-encoded image data (e.g., 'data:image/png;base64,...').
     * Either `image` or `base64` may be supplied by the callback.
     *
     * @type {string}
     */
    image?: string;
    /**
     * Base64-encoded image data (e.g., 'data:image/png;base64,...').
     * When provided, this is preferred and will be stripped before workbook insertion.
     *
     * @type {string}
     */
    base64?: string;
    /**
     * The row index of the top-left cell in the merged range.
     *
     * @type {number}
     */
    row?: number;
    /**
     * The column index of the top-left cell in the merged range.
     *
     * @type {number}
     */
    column?: number;
    /**
     * The row index of the last cell in the merged range
     *
     * @type {number}
     */
    lastRow?: number;
    /**
     * The column index of the last cell in the merged range
     *
     * @type {number}
     */
    lastColumn?: number;

    /**
     * External URL to image resource
     *
     * @type {string}
     */
    url?: string;

    /**
     * Image height in pixels
     *
     * @type {number}
     */
    height: number;

    /**
     * Image width in pixels
     *
     * @type {number}
     */
    width: number;

    /**
     * Alternative text for accessibility
     *
     * @type {string}
     */
    altText?: string;
}

/**
 * Internal representation of the library worksheet Image shape.
 * This mirrors the Image class expected by @syncfusion/excel-export worksheets.
 * Kept in types so it can be referenced across the codebase.
 *
 * @private
 */
export interface LibraryImage {
    image: string;
    row: number;
    column: number;
    lastRow: number;
    lastColumn: number;
    width: number;
    height: number;
    horizontalFlip: boolean;
    verticalFlip: boolean;
    rotation: number;
    lastRowOffset: number;
    lastColOffset: number;
    firstRowOffset: number;
    firstColumnOffset: number;
}

/**
 * Defines hyperlink configuration for Excel cells.
 * Supports web URLs, email links (mailto), and display text customization.
 */
export interface ExcelHyperlink {
    /** Target URL or mailto link. */
    target: string;

    /** Text displayed in the cell if different from the target URL. */
    displayText?: string;
}

/**
 * Event arguments passed to the Excel query cell info callback.
 * Allows customization of individual cells during export via callback.
 *
 * @interface ExcelCellCustomizeArgs
 * @template T - Generic type for the data row object
 * @example
 * ```typescript
 * const onExcelQueryCellInfo = (args: ExcelCellCustomizeArgs<Employee>) => {
 *   if (args.column?.field === 'photo') {
 *     args.image = { base64: photoData, height: 50, width: 50 };
 *   }
 *   if (args.column?.field === 'email') {
 *     args.hyperLink = { target: `mailto:${args.value}` };
 *   }
 *   if (args.column?.field === 'salary') {
 *     args.numberFormat = '#,##0.00';
 *   }
 * };
 * ```
 */
export interface ExcelCellCustomizeArgs<T = Record<string, unknown>> {
    /**
     * The current cell data object (full row data)
     */
    data: T;

    /**
     * The cell value (current display value)
     *
     * @type {string | number | Date | null | undefined}
     */
    value: string | number | Date | null | undefined;

    /**
     * The column definition containing field, type, format, etc.
     *
     * @type {Record<string, unknown>}
     */
    column?: Record<string, unknown>;

    /**
     * Zero-based row index in the current view
     *
     * @type {number}
     */
    rowIndex: number;

    /**
     * Zero-based column index
     *
     * @type {number}
     */
    colIndex: number;

    /**
     * Set to customize cell image (replaces cell value with image).
     * Image takes precedence over cell value and hyperlink.
     *
     * @type {ExcelImage}
     */
    image?: ExcelImage;

    /**
     * Set to convert cell to hyperlink.
     * The cell value is displayed as link text unless overridden by displayText.
     *
     * @type {ExcelHyperlink}
     */
    hyperLink?: ExcelHyperlink;

    /**
     * Merge cells horizontally (across columns).
     * Must be at least 1. No overlapping merges allowed.
     *
     * @type {number}
     * @default 1
     */
    colSpan?: number;

    /**
     * Merge cells vertically (across rows).
     * Must be at least 1. No overlapping merges allowed.
     *
     * @type {number}
     * @default 1
     */
    rowSpan?: number;

    /**
     * Excel number format string for numeric values.
     * Takes precedence over auto-detected format.
     *
     * @type {string}
     * @default undefined (auto-detect based on value type)
     * @example
     * ```
     * '#,##0.00' - Currency with 2 decimals
     * '0%' - Percentage
     * 'yyyy-mm-dd' - Date format
     * '#,##0' - Integer with thousand separator
     * ```
     */
    numberFormat?: string;

    /**
     * Indicates if this row is a group header.
     * Group headers receive special styling and indentation.
     *
     * @type {boolean}
     * @default false
     */
    isGroupHeader?: boolean;

    /**
     * Group nesting level (0 = top-level group).
     * Affects indentation and styling of group headers.
     *
     * @type {number}
     * @default 0
     */
    groupLevel?: number;

    /**
     * Cell style including colors, fonts, borders, alignment, etc.
     * Use to apply custom styling beyond default group header formatting.
     *
     * @type {CellStyle}
     */
    style?: CellStyle;
}

/**
 * Event arguments passed to the before Excel export callback.
 * Allows modification of columns and data before export processing.
 * Mirrors PDF export's onBeforePdfExport for consistent API.
 *
 * @interface ExcelBeforeExportEvent
 * @template T - Generic type for the data source items
 * @example
 * ```typescript
 * const beforeExport = (event: ExcelBeforeExportEvent<Employee>) => {
 *   // Modify columns before export
 *   event.columns = event.columns.filter(col => col.field !== 'salary');
 *   // Modify data before export
 *   event.dataSource = event.dataSource.filter(emp => emp.status === 'Active');
 *   // Cancel export if needed
 *   if (event.dataSource.length === 0) {
 *     event.cancel = true;
 *   }
 * };
 * ```
 */
export interface ExcelBeforeExportEvent<T = Record<string, unknown>> {
    /**
     * Array of columns for export. Can be modified before export.
     *
     * @type {ColumnProps<T>[]}
     */
    columns: ColumnProps<T>[];

    /**
     * Data source for export. Can be modified before export.
     */
    dataSource: T[];

    /**
     * Export configuration settings.
     *
     * @type {ExcelExportSettings<T>}
     */
    config: ExcelExportSettings<T>;

    /**
     * Set to true to cancel the export operation.
     *
     * @type {boolean}
     * @default false
     */
    cancel: boolean;
}

/**
 * Event arguments passed to the after Excel export callback.
 * Notifies of export completion or failure.
 * Mirrors PDF export's onAfterPdfExport for consistent API.
 *
 * @interface ExcelAfterExportEvent
 * @template T - Generic type for the data source items
 * @example
 * ```typescript
 * const afterExport = (event: ExcelAfterExportEvent<Employee>) => {
 *   if (event.success) {
 *     console.log('Excel export completed successfully');
 *     // Access blob data when isBlob=true
 *     event.promise?.then((args) => {
 *       console.log('Blob available:', args.blobData);
 *     });
 *   } else {
 *     console.error('Export failed:', event.error);
 *   }
 * };
 * ```
 */
export interface ExcelAfterExportEvent<T = Record<string, unknown>> {
    /**
     * Export configuration settings.
     *
     * @type {ExcelExportSettings}
     */
    config: ExcelExportSettings<T>;

    /**
     * Indicates whether the export was successful.
     *
     * @type {boolean}
     */
    success: boolean;

    /**
     * Error object if export failed.
     *
     * @type {Error | null}
     */
    error?: Error | null;

    /**
     * Promise resolving to blob data when `isBlob` is true in settings.
     * Undefined when `isBlob` is false or not provided.
     *
     * @type {Promise<{ blobData: Blob }>}
     */
    promise?: Promise<{ blobData: Blob }>;
}

/**
 * Settings for controlling Excel export behavior.
 * Defines data source, callbacks, filename, and feature toggles.
 *
 * @interface ExcelExportSettings
 * @template T - Generic type for the data source items
 * @example
 * ```typescript
 * const settings: ExcelExportSettings<Employee> = {
 *   data: employees,
 *   columns: ['id', 'name', 'email', 'department', 'salary'],
 *   fileName: 'employees-2026',
 *   onExcelQueryCellInfo: (args) => {
 *     if (args.column?.field === 'email') {
 *       args.hyperLink = { target: `mailto:${args.value}` };
 *     }
 *     if (args.column?.field === 'salary') {
 *       args.numberFormat = '$#,##0.00';
 *     }
 *   }
 * };
 * ```
 */
export interface ExcelExportSettings<T = Record<string, unknown>> {
    /**
     * Array of data items to export, or a custom-binding response object with a `result` array.
     * Required when using `useExcelExport` without `gridRef`.
     * When `UseGridExcelExportOptions.gridRef` is provided, data is resolved from the grid automatically.
     *
     */
    data?: T[] | { result: T[]; count?: number; [key: string]: unknown };

    /**
     * Specifies which rows to include in the Excel export.
     *
     * - `All` (default) — Exports all rows from the full data source.
     * - `CurrentPage` — Exports only rows visible on the current page.
     * - `Custom` — Exports rows within the range defined by `customRange`.
     *
     * @type {ExcelExportRange}
     * @default 'All'
     */
    range?: ExcelExportRange;

    /**
     * Defines the custom row range when `range` is set to `Custom`.
     * Zero-based, inclusive `startRow` and `endRow` indices.
     *
     * @type {ExcelExportCustomRange}
     */
    customRange?: ExcelExportCustomRange;

    /**
     * Optional export-specific column customizations.
     * Allows overriding grid column properties for the exported file (width, alignment, etc.).
     * Properties specified here take precedence over grid column definitions.
     * Matched to grid columns by `field` property.
     * **Feature Parity with PDF Export:** Enables consistent column customization across export formats.
     *
     * @type {Partial<ColumnProps>[]}
     * @example
     * ```typescript
     * const settings: ExcelExportSettings<Employee> = {
     *   data: employees,
     *   columns: [
     *     { field: 'id', width: 80, headerText: 'ID' },
     *     { field: 'name', width: 150, textAlign: 'Left' },
     *     { field: 'email', width: 200, headerTextAlign: 'Center' }
     *   ]
     * };
     * ```
     */
    columns?: Partial<ColumnProps<T>>[];

    /**
     * Optional filename for the exported Excel file (without extension).
     * The .xlsx extension is added automatically.
     *
     * @type {string}
     * @default 'export'
     */
    fileName?: string;

    /**
     * When the exported row count exceeds this threshold, export is canceled with an error.
     * Useful for protecting users from very large Excel exports.
     *
     * @type {number}
     * @default undefined
     */
    maxRowsWarningThreshold?: number;

    /**
     * Callback triggered before Excel export begins.
     * Allows modification of columns and data before export processing.
     * Set `event.cancel = true` to abort the export.
     * **Feature Parity with PDF Export:** Mirrors onBeforePdfExport for consistent API.
     *
     * @type {(event: ExcelBeforeExportEvent) => void}
     * @example
     * ```typescript
     * onBeforeExcelExport: (event) => {
     *   // Filter columns for export
     *   event.columns = event.columns.filter(col => col.field !== 'password');
     *   // Filter data for export
     *   event.dataSource = event.dataSource.slice(0, 100); // Export first 100 rows
     * }
     * ```
     */
    onBeforeExcelExport?: (event: ExcelBeforeExportEvent<T>) => void;

    /**
     * Callback invoked for each cell during export.
     * Allows customization of cell appearance, content, and behavior.
     * Supports both synchronous and asynchronous callbacks (async functions and Promises are awaited).
     * Handlers execute in this order: Image → Hyperlink → Spanning → Formatting → Grouping.
     * Set any of: image, hyperLink, colSpan, rowSpan, numberFormat, style.
     *
     * @type {(args: ExcelCellCustomizeArgs) => void | Promise<void>}
     * @example
     * ```typescript
     * // Async callback for loading images from URLs
     * onExcelCellCustomize: async (args) => {
     *   if (args.column?.field === 'photo') {
     *     const base64 = await loadImageAsBase64(args.value);
     *     args.image = { base64, height: 60, width: 60 };
     *   }
     * }
     * ```
     */
    onExcelCellCustomize?: (args: ExcelCellCustomizeArgs<T>) => void | Promise<void>;

    /**
     * Callback triggered after Excel export completes or fails.
     * Notifies of export result and any errors.
     * **Feature Parity with PDF Export:** Mirrors onAfterPdfExport for consistent API.
     *
     * @type {(event: ExcelAfterExportEvent) => void}
     * @example
     * ```typescript
     * onAfterExcelExport: (event) => {
     *   if (event.success) {
     *     console.log('Export successful');
     *   } else {
     *     console.error('Export failed:', event.error?.message);
     *   }
     * }
     * ```
     */
    onAfterExcelExport?: (event: ExcelAfterExportEvent<T>) => void;

    /**
     * Include hidden columns in export.
     * Applies if grid has column visibility toggling enabled.
     *
     * @type {boolean}
     * @default false
     */
    includeHiddenColumns?: boolean;

    /**
     * Theme to apply to exported cells (e.g., 'Material', 'Bootstrap', 'Fluent').
     * Affects default colors and styling.
     *
     * @type {string}
     * @default 'default'
     */
    theme?: ExcelTheme;

    /**
     * Header configuration for adding custom header rows above grid data.
     * Allows company branding, titles, and metadata at the top of the export.
     *
     * @example
     * ```typescript
     * header: {
     *   headerRows: 3,
     *   rows: [
     *     { cells: [{ colSpan: 4, value: 'Traders', style: { bold: true, fontSize: 20 } }] },
     *     { cells: [{ colSpan: 4, value: 'Sales Report 2026', style: { bold: true } }] },
     *     { cells: [{ colSpan: 4, value: '' }] } // Spacing row
     *   ]
     * }
     * ```
     */
    header?: ExcelHeader;

    /**
     * Footer configuration for adding custom footer rows below grid data.
     * Allows company info, disclaimers, or contact information at the bottom of the export.
     *
     * @example
     * ```typescript
     * footer: {
     *   footerRows: 2,
     *   rows: [
     *     { cells: [{ colSpan: 4, value: 'Thank you for your business!', style: { bold: true } }] },
     *     { cells: [{ colSpan: 4, value: 'Visit Again!', style: { bold: true } }] }
     *   ]
     * }
     * ```
     */
    footer?: ExcelFooter;

    /**
     * Export mode for the generated Excel file.
     * When `false` or not provided, the file is downloaded automatically.
     * When `true`, the generated Blob is returned for custom handling (e.g., upload, in-memory processing).
     *
     * @type {boolean}
     * @default false
     * @example
     * ```typescript
     * // Download the file automatically
     * await excelExport({ data: employees, isBlob: false });
     *
     * // Return Blob for custom handling
     * const blob = await excelExport({ data: employees, isBlob: true });
     * await uploadToServer(blob);
     * ```
     */
    isBlob?: boolean;
}

/**
 * Defines the theme for Excel export, including header, record, and caption styles.
 */
export interface ExcelTheme {
    /** Defines the style of header content. */
    header?: ExcelStyle;
    /** Defines the theme style of record content. */
    record?: ExcelStyle;
    /** Defines the theme style of caption content. */
    caption?: ExcelStyle;
}

/**
 * Defines Excel horizontal alignment.
 * ```props
 * * Left :- Aligns excel content to left.
 * * Right :- Aligns excel content to right.
 * * Center :- Aligns excel content to center.
 * * Fill :- Aligns excel content to fill.
 * ```
 */
export type ExcelHAlign = 'Left' | 'Right' | 'Center' | 'Fill';

/**
 * Defines Excel vertical alignment.
 * ```props
 * * Top :- Aligns excel content to top.
 * * Bottom :- Aligns excel content to bottom.
 * * Center :- Aligns excel content to center.
 * * Justify :- Aligns excel content to justify.
 * ```
 */
export type ExcelVAlign = 'Top' | 'Bottom' | 'Center' | 'Justify';

/**
 * Defines Excel cell style including font, alignment, borders, and formatting.
 */
export interface ExcelStyle {
    /** Defines the color of font */
    fontColor?: string;
    /** Defines the name of font */
    fontName?: string;
    /** Defines the size of font */
    fontSize?: number;
    /** Defines the horizontal alignment for cell style */
    hAlign?: ExcelHAlign;
    /** Defines the vertical alignment for cell style */
    vAlign?: ExcelVAlign;
    /** Defines the rotation degree for cell style */
    rotation?: number;
    /** Defines the bold style for fonts  */
    bold?: boolean;
    /** Defines the indent for cell style */
    indent?: number;
    /** Defines the italic style for fonts */
    italic?: boolean;
    /** Defines the underline style for fonts */
    underline?: boolean;
    /** Defines the background color for cell style */
    backColor?: string;
    /** Defines the wrapText for cell style */
    wrapText?: boolean;
    /** Defines the borders for cell style */
    borders?: ExcelBorder;
    /** Defines the format of the cell */
    numberFormat?: string;
    /** Defines the type of the cell */
    type?: string;
    /** Defines the strike through of the cell */
    strikeThrough?: boolean;
}

/**
 * Defines the border properties for Excel cells.
 */
export interface ExcelBorder {
    /**  Defines the color of border */
    color?: string;
    /**  Defines the line style of border */
    lineStyle?: ExcelBorderLineStyle;
}

/**
 * Defines excel border line style.
 * ```props
 * * thin :- Excel border line style as thin line.
 * * thick :- Excel border line style as thick line.
 * ```
 */
export type ExcelBorderLineStyle = 'thin' | 'thick';

/**
 * Row definition for Excel export headers and footers.
 * Defines a single row with cells, each cell can span multiple columns.
 *
 * @private
 */
export interface ExcelHeaderFooterRow {
    /**
     * Array of cells in this row.
     */
    cells: Array<{
    /**
     * Number of columns this cell spans.
     *
     * @type {number}
     * @default 1
     */
        colSpan?: number;

        /**
         * Cell value (text content).
         */
        value?: string;

        /**
         * Hyperlink in the cell.
         */
        hyperlink?: ExcelHyperlink;

        /**
         * Cell styling (background color, font, alignment, etc.).
         */
        style?: CellStyle;
    }>;
}

/**
 * Header configuration for Excel export.
 * Adds custom header rows above the grid data.
 */
export interface ExcelHeader {
    /**
     * Total number of header rows to reserve.
     */
    headerRows: number;

    /**
     * Array of header row definitions.
     */
    rows: ExcelHeaderFooterRow[];
}

/**
 * Footer configuration for Excel export.
 * Adds custom footer rows below the grid data.
 */
export interface ExcelFooter {
    /**
     * Total number of footer rows to reserve.
     */
    footerRows: number;

    /**
     * Array of footer row definitions.
     */
    rows: ExcelHeaderFooterRow[];
}

/**
 * Configuration for grouping data during Excel export.
 * Enables hierarchical data representation in exported sheets.
 *
 * @private
 */
export interface ExcelGroupingSettings {
    /**
     * Array of column field names to group by.
     * Grouping is applied in order of precedence (first column = top-level groups).
     *
     * @type {string[]}
     * @example ['department', 'status'] groups first by department, then by status
     */
    groupByColumns: string[];

    /**
     * Enable/disable grouping.
     * When false, grouping configuration is ignored.
     *
     * @type {boolean}
     * @default true
     */
    enabled?: boolean;

    /**
     * Group header background color in hex format.
     * Applied to all group header rows regardless of level.
     *
     * @type {string}
     * @default '#E8E8E8'
     */
    headerBackgroundColor?: string;

    /**
     * Make group header text bold.
     * Enhances visual distinction of group headers.
     *
     * @type {boolean}
     * @default true
     */
    boldHeaders?: boolean;
}
