export const COMMON_CLASSES: Record<string, string> = {
    CONTROL: 'sf-control',
    RTL: 'sf-rtl',
    DISABLED: 'sf-disabled',
    FOCUSED: 'sf-focused',
    HOVERED: 'sf-hovered',
    ELLIPSIS: 'sf-ellipsis',
    ICON: 'sf-icon',
    ICON_SIZE: 'sf-icon-size',
    SUBMENU_ICON: 'sf-submenu-icon',
    MENU_ICON: 'sf-menu-icon',
    URL: 'sf-menu-url',
    ALIGN_CENTER: 'sf-align-center',
    SEPARATOR: 'sf-separator',
    ANCHOR_WRAP: 'sf-anchor-wrap',
    CHEVRON_DOWN: 'sf-chevron-down',
    CHEVRON_LEFT: 'sf-chevron-left',
    CHEVRON_RIGHT: 'sf-chevron-right',
    HEADER: 'sf-menu-header',
    HAS_SUBMENU: 'sf-has-submenu',
    ITEM: 'sf-menu-item',
    ITEM_LABEL: 'sf-menu-item-label',
    UL: 'sf-menu-ul'
};

export const MENU_CLASSES: Record<string, string> = {
    ROOT: 'sf-menu',
    HORIZONTAL: 'sf-menu-horizontal',
    VERTICAL: 'sf-menu-vertical',
    PARENT: 'sf-menu-parent',
    SUBMENU: 'sf-menu-submenu',
    ROOT_LIST: 'sf-menu-root',
    BASE: 'sf-menu-base',
    SUBMENU_WRAPPER: 'sf-submenu-wrapper'
};

export const CONTEXTMENU_CLASSES: Record<string, string> = {
    ROOT: 'sf-contextmenu'
};

export const TABS_CLASSES: Record<string, string> = {
    ROOT: 'sf-tabs',
    TOP: 'sf-tabs-top',
    BOTTOM: 'sf-tabs-bottom',
    LEFT: 'sf-tabs-left',
    RIGHT: 'sf-tabs-right',
    HORIZONTAL: 'sf-tabs-horizontal',
    VERTICAL: 'sf-tabs-vertical',
    HAS_INDICATOR: 'sf-tabs-has-indicator',
    SCROLLABLE: 'sf-tabs-scrollable',
    POPUP: 'sf-tabs-popup',
    DEFAULT_VARIANT: 'sf-tabs-default',
    FILL: 'sf-tabs-fill',
    ACCENT: 'sf-tabs-accent',
    SMALL: 'sf-tabs-small',
    MEDIUM: 'sf-tabs-medium',
    LARGE: 'sf-tabs-large',
    LIST: 'sf-tablist',
    LIST_HORIZONTAL: 'sf-tablist-horizontal',
    LIST_VERTICAL: 'sf-tablist-vertical',
    TAB: 'sf-tab',
    TAB_SELECTED: 'sf-tab-selected',
    TAB_FOCUSED: 'sf-tab-focused',
    TAB_DISABLED: 'sf-tab-disabled',
    TAB_HAS_CLOSE: 'sf-tab-has-close',
    TAB_CLOSE: 'sf-tab-close',
    OVERFLOW: 'sf-tabs-overflow',
    OVERFLOW_TRIGGER: 'sf-tabs-overflow-trigger',
    OVERFLOW_OPEN: 'sf-tabs-overflow-open',
    POPUP_ITEMS: 'sf-tabs-popup-items',
    OVERFLOW_ITEM: 'sf-tab-overflow-item',
    OVERFLOW_ITEM_ACTIVE: 'sf-tab-overflow-item-active',
    PANELS: 'sf-tabpanels',
    PANEL: 'sf-tabpanel',
    PANEL_ACTIVE: 'sf-tabpanel-active',
    PANEL_ANIMATING: 'sf-tabpanel-animating',
    INDICATOR: 'sf-tab-indicator',
    INDICATOR_HORIZONTAL: 'sf-tab-indicator-horizontal',
    INDICATOR_HORIZONTAL_BOTTOM: 'sf-tab-indicator-horizontal-bottom',
    INDICATOR_VERTICAL: 'sf-tab-indicator-vertical',
    INDICATOR_VERTICAL_RIGHT: 'sf-tab-indicator-vertical-right',
    POS_ABSOLUTE: 'sf-pos-absolute',
    NO_POINTER: 'sf-no-pointer',
    POS_RELATIVE: 'sf-pos-relative',
    DISPLAY_FLEX: 'sf-display-flex',
    DISPLAY_INLINE_FLEX: 'sf-display-inline-flex',
    ALIGN_CENTER: 'sf-align-center',
    PREVENT_SELECT: 'sf-prevent-select',
    NOWRAP: 'sf-nowrap',
    OVERFLOW_AUTO: 'sf-overflow-auto',
    CURSOR_NOT_ALLOWED: 'sf-cursor-not-allowed',
    CURSOR_POINTER: 'sf-cursor-pointer',
    TAB_LABEL: 'sf-tab-label'
};

export const TREE_VIEW_CLASSES: Record<string, string> = {
    ROOT: 'sf-treeview',
    LIST: 'sf-treeview-list',
    ITEM: 'sf-treeview-item',
    ITEM_CONTENT: 'sf-treeview-item-content',
    ITEM_LABEL: 'sf-treeview-item-label',
    ITEM_ICON: 'sf-treeview-item-icon',
    ITEM_TOGGLE: 'sf-treeview-item-toggle',
    ITEM_TOGGLE_EXPANDED: 'sf-treeview-item-toggle-expanded',
    ITEM_DEFAULT_TOGGLE: 'sf-treeview-default-toggle',
    ITEM_CHECKBOX: 'sf-treeview-item-checkbox',
    ITEM_ACTION: 'sf-treeview-item-action',
    LOADING_INDICATOR: 'sf-treeview-loading-spinner',
    EMPTY_STATE: 'sf-treeview-empty',
    EXPANDED: 'sf-treeview-item-expanded',
    COLLAPSED: 'sf-treeview-collapsed',
    SELECTED: 'sf-treeview-item-selected',
    PARTIALLY_SELECTED: 'sf-treeview-partially-selected',
    DISABLED: 'sf-treeview-item-disabled sf-disabled',
    LEAF: 'sf-treeview-leaf',
    LOADING: 'sf-treeview-loading-active',
    EDITING: 'sf-treeview-editing',
    FOCUSED: 'sf-treeview-item-focused',
    RTL: 'sf-treeview-rtl',
    CONTENT_CENTER: 'sf-content-center',
    CONTENT: 'sf-content',
    ROOT_LEAF_ITEM: 'sf-treeview-root-leaf',
    EDIT_INPUT: 'sf-treeview-edit-input',
    EDIT_INPUT_WRAPPER: 'sf-treeview-edit-input-wrapper',
    ITEM_LINK: 'sf-treeview-item-link sf-link',
    ITEM_LABEL_NO_WRAP: 'sf-nowrap',
    ITEM_LINK_FULL_ROW: 'sf-treeview-link-full-row',
    ROW_SURFACE: 'sf-treeview-row-surface sf-pos-relative'
};
